/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petri_net_Patients;

import PetriNet.PetriNet;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import javax.swing.border.Border;

/**
 *
 * @author dogboy
 */
public class Petrinet_Patients extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Petrinet_Patients() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_transition.setBorder(label_border);
        jLabel_transition.setForeground(Color.white);
        jLabel_transition1.setBorder(label_border);
        jLabel_transition1.setForeground(Color.white);
//        exitbutton.setBorder(label_border);
    }
    public static int wt = 0, id = 0, id1 = 0, dn = 0; 
    private Auto_Fire t;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitbutton = new javax.swing.JLabel();
        jLabel_transition1 = new javax.swing.JLabel();
        jLabel_transition = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        Name2 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        marking = new javax.swing.JTextField();
        firing = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new RoundedPanel(90, Color.WHITE);
        Wait = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(90, Color.WHITE);
        Inside = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(90, Color.WHITE);
        Done = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exitbutton2 = new javax.swing.JLabel();

        exitbutton.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(24, 30, 40));
        exitbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbutton.setText("X");
        exitbutton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(35, 41, 52))); // NOI18N
        exitbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbuttonMouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel_transition1.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel_transition1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(27, 34, 45))); // NOI18N
        jLabel_transition1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_transition1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_transition1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_transition1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_transition1MouseExited(evt);
            }
        });

        jLabel_transition.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel_transition.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(27, 34, 45))); // NOI18N
        jLabel_transition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_transition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_transitionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_transitionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_transitionMouseExited(evt);
            }
        });

        text1.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        text1.setText("0");
        text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text1KeyTyped(evt);
            }
        });

        Name1.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        Name1.setText("Wait");

        text2.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        text2.setText("0");
        text2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text2KeyTyped(evt);
            }
        });

        Name2.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        Name2.setText("Inside");

        Name3.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        Name3.setText("Done");

        text3.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        text3.setText("0");
        text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text3ActionPerformed(evt);
            }
        });
        text3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text3KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        jButton1.setText("Set token");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Start");

        jLabel5.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel5.setText("Change");

        jLabel6.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel6.setText("------->");

        jLabel7.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel7.setText("------->");

        jLabel8.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel8.setText("------->");

        jLabel9.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel9.setText("------->");

        jLabel10.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel10.setText("Firing");

        jLabel11.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel11.setText("Marking");

        marking.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N
        marking.setText("[0.Wait,0.Inside,0.Done]");

        firing.setFont(new java.awt.Font("Hack Nerd Font", 3, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel12.setText("Wait");

        jLabel13.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Inside");

        jLabel14.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel14.setText("Done");

        jToggleButton1.setBackground(new java.awt.Color(44, 218, 92));
        jToggleButton1.setFont(new java.awt.Font("Hack Nerd Font", 1, 18)); // NOI18N
        jToggleButton1.setText("ON");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jLabel15.setText("Auto Fire");

        jButton2.setFont(new java.awt.Font("Hack Nerd Font", 3, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Wait.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        Wait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wait.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Wait, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Wait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        Inside.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        Inside.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inside.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Inside, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inside, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        Done.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        Done.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Done.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Done, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Done, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Hack Nerd Font", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PETRI NET");

        exitbutton2.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        exitbutton2.setForeground(new java.awt.Color(24, 30, 40));
        exitbutton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbutton2.setText("X");
        exitbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbutton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbutton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbutton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbutton2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1)
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_transition, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firing, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(marking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Name3)
                                .addGap(2, 2, 2)
                                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel_transition1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(78, 78, 78))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(352, 352, 352)
                .addComponent(jLabel11)
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(Name1)
                .addGap(3, 3, 3)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(Name2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_transition, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_transition1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_transition1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transition1MouseClicked
        
        dn = Integer.parseInt(Done.getText());
        id = Integer.parseInt(Inside.getText());
        
        if (id > 0) {
            id -= 1;
            dn += 1;
        }
        
        Done.setText(String.valueOf(dn));
        Inside.setText(String.valueOf(id));
        
        firing.setText("Change");
        Marking();
    }//GEN-LAST:event_jLabel_transition1MouseClicked

    private void jLabel_transition1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transition1MouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        jLabel_transition1.setBorder(label_border);
        jLabel_transition1.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_transition1MouseEntered

    private void jLabel_transition1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transition1MouseExited
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_transition1.setBorder(label_border);
        jLabel_transition1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_transition1MouseExited

    private void jLabel_transitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transitionMouseClicked
        
        wt = Integer.parseInt(Wait.getText());
        id = Integer.parseInt(Inside.getText());
        
        if (wt > 0) {
            wt -= 1;
            id += 1;
        }
        
        Wait.setText(String.valueOf(wt));
        Inside.setText(String.valueOf(id));
        
        firing.setText("Start");
        Marking();
        
    }//GEN-LAST:event_jLabel_transitionMouseClicked

    private void jLabel_transitionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transitionMouseEntered
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
        jLabel_transition.setBorder(label_border);
        jLabel_transition.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_transitionMouseEntered

    private void jLabel_transitionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_transitionMouseExited
        
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_transition.setBorder(label_border);
        jLabel_transition.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_transitionMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (t != null) {
            
            t.cancel(true);
            t = null;
            jButton1.setEnabled(true);
        }
        
        wt = Integer.parseInt(text1.getText());
        id = Integer.parseInt(text2.getText());
        dn = Integer.parseInt(text3.getText());
        
        if (wt >= 0 && id >= 0 && dn >= 0) {
            
            Wait.setText(String.valueOf(wt));
            Inside.setText(String.valueOf(id));
            Done.setText(String.valueOf(dn));
            if (wt == 0 && id == 0 && dn == 0) jButton1.setEnabled(true);
            else jButton1.setEnabled(false);
            
            if (jToggleButton1.getText().equals("OFF")) {
                
                jToggleButton1.doClick();
                jToggleButton1.setBackground(Color.green);
            }
        }
        
        Marking();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
        if (jToggleButton1.isSelected()) {
            
            jToggleButton1.setText("OFF");
            jToggleButton1.setBackground(Color.red);
            
            jButton1.setEnabled(true);
            
            (t = new Auto_Fire()).execute();
             
        }
        else {
            
            jToggleButton1.setText("ON");
            jToggleButton1.setBackground(Color.green);
            
            if (t != null) {
            
                t.cancel(true);
                t = null;
                jButton1.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Wait.setText("0");
        Inside.setText("0");
        Done.setText("0");
        firing.setText("");
        Marking();
        text1.setText("0");
        text2.setText("0");
        text3.setText("0");
        
        if (jToggleButton1.getText().equals("OFF")) {
                
                jToggleButton1.doClick();
                jToggleButton1.setText("ON");
                jToggleButton1.setBackground(Color.green);
            }
        
        if (t != null) {
            
            t.cancel(true);
            t = null;
            
        }
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void text1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text1KeyTyped
        
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_text1KeyTyped

    private void text2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text2KeyTyped
        
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_text2KeyTyped

    private void text3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text3KeyTyped
        
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_text3KeyTyped

    private void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseClicked
        // TODO add your handling code here:
        PetriNet ptr = new PetriNet();
        ptr.setVisible(true);
        ptr.pack();
        ptr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_exitbuttonMouseClicked

    private void exitbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseEntered
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        exitbutton.setBorder(border);
        exitbutton.setForeground(Color.white);
    }//GEN-LAST:event_exitbuttonMouseEntered

    private void exitbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseExited
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        exitbutton.setBorder(border);
        exitbutton.setForeground(Color.black);
    }//GEN-LAST:event_exitbuttonMouseExited

    private void exitbutton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbutton2MouseClicked
        // TODO add your handling code here:
        PetriNet ptr = new PetriNet();
        ptr.setVisible(true);
        ptr.pack();
        ptr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_exitbutton2MouseClicked

    private void exitbutton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbutton2MouseEntered
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        exitbutton.setBorder(border);
        exitbutton.setForeground(Color.white);
    }//GEN-LAST:event_exitbutton2MouseEntered

    private void exitbutton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbutton2MouseExited
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        exitbutton.setBorder(border);
        exitbutton.setForeground(Color.black);
    }//GEN-LAST:event_exitbutton2MouseExited
    
    public void Marking() {
        
        String w = Wait.getText(), i = Inside.getText(), d = Done.getText();
        marking.setText("[" + w + ".Wait," + i + ".Inside," + d + ".Done]");
    }
    
    private class Auto_Fire extends SwingWorker<Void, String> {
        
        @Override
        protected Void doInBackground() throws InterruptedException {
            
            wt = Integer.parseInt(Wait.getText());
            id = Integer.parseInt(Inside.getText());
            dn = Integer.parseInt(Done.getText());
            boolean found = false;
            
            while(!isCancelled() && !found) {
                
                
                while (wt > 0) {   
                    firing.setText("Start");
                    wt -= 1;
                    Wait.setText(String.valueOf(wt));
                    
                    id++;
                    Inside.setText(String.valueOf(id));
                    
                    Marking();
                    Thread.sleep(1000);
                    
                    
                }
                
                while (id > 0) {
                    firing.setText("Change");
                    id -= 1;
                    Inside.setText(String.valueOf(id));
                    
                    dn += 1;
                    Done.setText(String.valueOf(dn));
                    
                    Marking();
                    Thread.sleep(1000);
                }
                
                jButton1.setEnabled(true);
                
                found = true;
            }
            return null;
        }
        
        @Override
        protected void done() {}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petrinet_Patients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Done;
    private javax.swing.JLabel Inside;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Wait;
    private javax.swing.JLabel exitbutton;
    private javax.swing.JLabel exitbutton2;
    private javax.swing.JTextField firing;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_transition;
    private javax.swing.JLabel jLabel_transition1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField marking;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    // End of variables declaration//GEN-END:variables

}
